### ISSUE TITLE
Getting error after adding this library in build.gradle

### ISSUE THREAD

**Issue by masudias** [j2esu/rv-joiner#11]
This error found while syncing after adding the library.
Error:(5, 5) No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').

**Comment by j2esu** [comment]
Hi. What are your gradle dependencies? Try to clean project and use this:

compile 'com.android.support:appcompat-v7:23.2.0'
compile 'com.android.support:recyclerview-v7:23.2.0'
