### ISSUE TITLE
Seems like adapters don't work separately in my case

### ISSUE THREAD

**Issue by sough** [j2esu/rv-joiner#17]
With this code

    rvJoiner.add(new JoinableLayout(R.layout.part_video_search_casts_section, TITLE_TYPE));
    rvJoiner.add(new JoinableAdapter(mPersonAdapter, CASTS_CONTENT_TYPE));

I have the following error

    java.lang.ClassCastException: su.j2e.rvjoiner.JoinableLayout$Adapter$LayoutVh 
        cannot be cast to kz.dar.eco.darplay.adapter.SearchPersonsAdapter$SearchViewHolder
        at kz.dar.eco.darplay.adapter.SearchPersonsAdapter.onBindViewHolder

**Comment by vyapariapp** [comment]
i have same error , How did you solve?

**Comment by vyapariapp** [comment]
reopen this please

**Comment by vyapariapp** [comment]
@sough how did you solve this error?

**Comment by midhilajm** [comment]
same issue how to solve?
